### ISSUE TITLE
LargestContentfulPaint is difficult to efficiently implement

### ISSUE THREAD

**Issue by progers** [w3c/largest-contentful-paint#31]
Browsers use a threaded compositing model where the DOM is processed on one thread (in chromium this is the "main thread") and is later displayed on a different thread (in chromium this is the "compositor thread"). This makes the concept of "paint"-time (or renderTime) difficult to determine.

This is problematic because the main thread will "paint" content that is not currently visible in case it becomes visible on the compositor thread. Similarly, the compositor thread will "raster" content that is clipped or occluded due to the cost of calculating visibility. It is not possible to correctly calculate renderTime, from the user's perspective, in an efficient way in chromium. This is almost certainly true for other engines.

IntesectionObserverV2 has a similar issue and, for this reason, the spec was updated to say "If the implementation cannot guarantee that the target is completely unoccluded by other page content, return false" (see: [iov2 spec](https://w3c.github.io/IntersectionObserver/v2/#calculate-visibility-algo)).

Could the spec be updated to explicitly say that the timing used by LargestContentfulPaint is best-effort or an approximation?

**Comment by chrishtr** [comment]
Just read through the Element Timing spec.

It uses the "IOv1" notion of visible, which is whether the element is painted in a location
that is on the screen. However, it may still be occluded partially or completely, or have a filter or
opacity applied to it that makes it not visible. I discussed w @progers  and @szager the possibility of using the "IOv2" notion, which takes into account those effects.

the "IOv2" notion is more expensive to compute, though the parts about opacity, transform and
filter are efficient. It's not totally clear to me, though, that the IOv2 notion is a better approach, because it would mean that e.g. a page which loads & paints everything with low opacity, then fades in content, will get a very strange LCP metric result.

Also, regarding the compositor comment @progers raised, yes it's true that the latency of the pipeline stages off of the main thread is not taken into account with a simple implementation, but I'm not sure that latency is a big problem, since that latency is much less than total page load time.

**Comment by npm1** [comment]
All of the algorithms in https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering are also related to rendering timing. I think it's understood that the timing is not 100% accurate (in fact, timestamps need to be clamped), but does that mean we need to add "best-effort or an approximation" in all of those algorithms? Or am I missing what's different here?

**Comment by progers** [comment]
The issue with threading is not about the exact times produced (e.g., whether gpu raster time is included), it is that "renderTime" is not defined. Furthermore, it would be difficult to efficiently implement a concept of "renderTime" that even approximates the spec's language of "displayed on screen".

A simple example of this is a compositor-thread opacity animation from 0 to 1 which is a common loading effect:
  1. The main thread will paint the content and pass it to the compositor thread, but the opacity is still 0.
  2. The compositor thread will then change the opacity to 1 so the content becomes visible to the user.

From the user's perspective, the content is not rendered at 1. In a threaded browser, is difficult to efficiently notify the main thread when visibility on the compositor thread changes at step 2. For an example of why this is difficult to do efficiently, consider more difficult composited animation cases than just opacity, such as animating transforms for complex content under clips.

If the [update-the-rendering](https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering) spec language is followed, the example above (animating opacity 0 to 1) would have "updated" rendering at the first step, with opacity 0.

If the [IOv1 intersection rect](https://w3c.github.io/IntersectionObserver/#calculate-intersection-rect-algo) spec language is followed, opacity effects are ignored so the example above (animating opacity 0 to 1) would have an intersection rect time at the first step, with opacity 0.

If the [IOv2 intersection rect](https://w3c.github.io/IntersectionObserver/v2/#calculate-visibility-algo) spec language is followed, the result would be "best-effort".

**Comment by chrishtr** [comment]
Another issue is that whether elements are "painted" at all may depend on the browser.

Considering again the fade-in web UI example @progers mentioned: if the content starts out at opacity:0 and then animates to opacity: 1, the browser may choose to simply not paint the content at the beginning, and only start painting it once it begins to animate to a visible opacity value.

However, I see that the Element Timing spec has an [images pending rendering](https://wicg.github.io/element-timing/#images-pending-rendering) definition (and similar for text), which only says that they are "ready for rendering", not that they are actually rendered. Further, it uses the IOv1 notion of viewport visibility. The spec does seem clear and specified independently of whether paint actually occurs for an element.

Now back to considering the IOv2 definition of visibility, at least as it concerns transforms and opacity: I think I was wrong about the fade-in example being weird. If a site loads a large image that is opacity:0, and then only a while later starts to fade it in, and LCP timing happens when that fade-in starts to actually show the image, then that seems like a good thing, and a more accurate measure.

I think it would be good for LCP to take into account opacity, transform and other similar effects which may result in the object not really being visible. For transform, an example would be a rotation about the Z and Y axis that results in the quad being nearly invisible, but still have a large bounding rect in viewport space. Transforms may be acceptable if the spec changes to a "quad bounding box" instead of bounding rectangle.

Maybe it would be useful to check for occlusion also, which is the other part of IOv2 notions of visibility, but that is more expensive to compute. However, taking it into account occlusion will 
lead to a more accurate result in some cases. An example would be a large image which is occluded because it's behind a viewport-sized, opaque div that is a sibling of the image in the DOM.

**Comment by npm1** [comment]
We can add some easy to compute checks in the spec for now. Opacity, display:none, and visibility: hidden... Any others? I think we already actually implement some of it this way in Chrome and we have this test but it may not be comprehensive: https://github.com/web-platform-tests/wpt/blob/master/element-timing/invisible-images.html

**Comment by chrishtr** [comment]
From items 1-4 [here](https://w3c.github.io/IntersectionObserver/v2/#calculate-visibility-algo), I suggest Effective Opacity < 0.??; filters which affect opacity.

I'm not sure about transforms. Maybe the definition in step 2 from the link above suffices, as it excludes any of the more complicated cases.

**Comment by progers** [comment]
I think we should avoid trying to specify the delta between "ready for rendering" and "displayed on screen". Effects such as masks and filters can be equivalent to `opacity: 0` but are intractable to check. A more perverse example is that there is no code in chromium to determine if a sufficiently large 'O' character centered on the screen actually fills any pixels.

Would it be reasonable to just state that LargestContentfulPaint should, best-effort, exclude content that will not be displayed on the screen?

**Comment by chrishtr** [comment]
> I think we should avoid trying to specify the delta between "ready for rendering" and "displayed on screen".

Sure, but the spec already avoids this. It uses the time when the image or text is "ready for rendering".

> Would it be reasonable to just state that LargestContentfulPaint should, best-effort, exclude content that will not be displayed on the screen?

I don't think it's a good idea to introduce a best-effort heuristic if we can avoid it.

**Comment by progers** [comment]
@chrishtr, does a spec explicitly call out "ready for rendering" or is that implicit from ElementTiming being updated via the ["update-the-rendering"](https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering) step? The IOv1 definition of visibility includes transforms. If there is an active transform animation, does the ["intersection rect algorithm"](https://w3c.github.io/IntersectionObserver/#calculate-intersection-rect-algo) need to be run on every frame? Would this defeat the purpose of threaded animations?

**Comment by chrishtr** [comment]
Re "ready for rendering": the Element Timing spec [defines](https://wicg.github.io/element-timing/#process-an-image-that-finished-loading) how to add an image to a list of images that are [pending rendering](https://wicg.github.io/element-timing/#images-pending-rendering).

I think the spec is pretty clear - when an image becomes pending-rendering, then compute its viewport intersection in the next frame and adjust the LargestContentfulPaint metric accordingly.

Re animation: yes this is a problem, if that were taken into account. It's also a problem for animating opacity. Handling that may have quite bad performance.

Coming back to the opacity example, it seems we either have to account for opacity animations, or ignore opacity.

**Comment by progers** [comment]
With a closer reading of the spec, my concerns are now resolved. @chrishtr pointed out the spec does define "renderTime" as being the time that [update-the-rendering](https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering) runs. The issues of animating effects and transforms are not feasible to solve because of the threaded performance implications, so I think we should ignore them, as they are already (implicitly). For example, if transform is "translate(100px, 0)" at "renderTime", consider it as "translate(100px, 0)". If a running CSS animation later changes the transform to "translate(10px, 0)", pick up this change when [update-the-rendering](https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering) runs next. Lastly, it is not feasible to ignore painting of filters, opacity, or masks, so these effects can be ignored (as they are in the ["intersection rect algorithm"](https://w3c.github.io/IntersectionObserver/#calculate-intersection-rect-algo) already).

If this is true and good, we should remove the opacity checks from the chromium implementation, or add spec language that says opacity 0 should be ignored. I think this issue can then be closed.

**Comment by npm1** [comment]
It seems to me that we could add the checks in https://w3c.github.io/IntersectionObserver/v2/#calculate-visibility-algo to the LCP spec, though I'm not sure these are all being checked at the moment in the Chromium implementation (and hence unsure if these will be fast enough). @maxlgu do you know?

**Comment by maxlgu** [comment]
These are not checked at the moment.

**Comment by maxlgu** [comment]
I think LCP doesn't have any of these check. Here's the explanation for each of the checks:

1. If the observer’s trackVisibility attribute is false, return true.
- N/A for LCP
2. If the target has an effective transformation matrix other than a 2D translation or proportional 2D upscaling, return false.
- N/A for LCP
3. If the target, or any element in its containing block chain, has an effective opacity other than 100%, return false.
- LCP regards opacity == 0 as invisible, but regards opacity > 0 as visible
4. If the target, or any element in its containing block chain, has any filters applied, return false.
- When the paint pipeline still has to paint the elements with the applied filters, they are visible to LCP. Because not every filters will block the paint pipeline, I believe LCP does not apply this check.
5. If the implementation cannot guarantee that the target is completely unoccluded by other page content, return false.
- This condition errs on reporting invisible unless the target is proved to be completely unoccluded. LCP errs on regarding an element as visible unless it's ignored by the paint pipeline. So this check also doesn't apply to LCP.

**Comment by yoavweiss** [comment]
I believe we can now close this issue, as there are no pending action items related to it.
